apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: loki
spec:
  input:
    application:
      namespaces:
        system: true
  output:
    custom: |
      name   loki
      host   {release-name}-headless.{namespace}.svc.cluster.local
      port   3100
      labels job=fluentbit
      auto_kubernetes_labels on