loki:
  podLabels:
    # enable istio sidecar injection
    sidecar.istio.io/inject: "true"
  # configure the filesystem storage
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  # disable multi-tenancy
  auth_enabled: false
  limits_config:
    # reduce the ingestion rate to avoid crashing the lightweight setup
    ingestion_rate_mb: 3
  # increase retention time to 5 days
  chunk_store_config:
    max_look_back_period: 120h
  table_manager:
    retention_deletes_enabled: true
    retention_period: 120h
# use single binary mode instead of scalable
singleBinary:
  replicas: 1

# Disable any additional components of the chart
test:
  enabled: false
monitoring:
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
gateway:
  enabled: false
