opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false

default:
  envOverrides:
  - name: OTEL_SERVICE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: "metadata.labels['app.kubernetes.io/name']"

components:
  accountingService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    initContainers:
      - name: wait-for-kafka
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z -v -w30 {{ include "otel-demo.name" . }}-kafka 9092; do echo waiting for kafka; sleep 2; done;']
        securityContext:
          runAsUser: 1337

  adService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    service:
      port: null
    ports:
      - name: grpc
        value: 8080

  cartService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    service:
      port: null
    ports:
      - name: grpc
        value: 8080
    initContainers:
      - name: wait-for-redis
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z -v -w30 {{ include "otel-demo.name" . }}-redis 6379; do echo waiting for redis; sleep 2; done;']
        securityContext:
          runAsUser: 1337

  checkoutService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    service:
      port: null
    ports:
      - name: grpc
        value: 8080
    initContainers:
      - name: wait-for-kafka
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z -v -w30 {{ include "otel-demo.name" . }}-kafka 9092; do echo waiting for kafka; sleep 2; done;']
        securityContext:
          runAsUser: 1337

  currencyService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    service:
      port: null
    ports:
      - name: grpc
        value: 8080

  emailService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4318/v1/traces'
    service:
      port: null
    ports:
      - name: http
        value: 8080

  featureflagService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    initContainers:
      - name: wait-for-ffspostgres
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z -v -w30 {{ include "otel-demo.name" . }}-ffspostgres 5432; do echo waiting for ffspostgres; sleep 2; done']
        securityContext:
          runAsUser: 1337

  frauddetectionService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    initContainers:
      - name: wait-for-kafka
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z -v -w30 {{ include "otel-demo.name" . }}-kafka 9092; do echo waiting for kafka; sleep 2; done;']
        securityContext:
          runAsUser: 1337

  frontend:
    enabled: true
    resources:
      limits:
        memory: 500Mi
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    service:
      port: null
    ports:
      - name: http
        value: 8080

  frontendProxy:
    enabled: true

  loadgenerator:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'

  paymentService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    service:
      port: null
    ports:
      - name: grpc
        value: 8080

  productCatalogService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    service:
      port: null
    ports:
      - name: grpc
        value: 8080

  quoteService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'telemetry-otlp-traces.kyma-system:4317'
    service:
      port: null
    ports:
      - name: http
        value: 8080

  recommendationService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    service:
      port: null
    ports:
      - name: grpc
        value: 8080

  shippingService:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'
    service:
      port: null
    ports:
      - name: grpc
        value: 8080

  ffsPostgres:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'

  kafka:
    enabled: true
    envOverrides:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://telemetry-otlp-traces.kyma-system:4317'

  redis:
    enabled: true