apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    labels:
        app.kubernetes.io/name: event-emitter
    name: event-emitter
    namespace: default
spec:
    runtime: nodejs18
    source:
      gitRepository: 
        url: https://github.com/kyma-project/examples.git
        baseDir: /incluster_eventing/src/emitter-fn/
        reference: main
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: incoming-http-trigger
  namespace: default
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: incoming
  rules:
  - accessStrategies:
    - handler: allow
    methods:
    - GET
    path: /.*
  service:
    name: event-emitter
    port: 80
