apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    labels:
        app.kubernetes.io/name: event-receiver
    name: event-receiver
    namespace: default
spec:
    runtime: nodejs18
    source:
      gitRepository: 
        url: https://github.com/kyma-project/examples.git
        baseDir: /incluster_eventing/src/receiver-fn/
        reference: main
---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: event-receiver
  namespace: default
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.acme.payload.sanitised.v1
  protocol: ""
  protocolsettings: {}
  sink: http://event-receiver.default.svc.cluster.local

