---
apiVersion: gateway.kyma.cx/v1alpha2
kind: Api
metadata:
  labels:
    function: hello
    example: gateway
  name: hello
spec:
  hostname: hello.kyma.local
  service:
    name: hello
    port: 8080