---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  labels:
    function: hello
    example: serverless-lambda
  name: hello
spec:
  authenticationEnabled: true
  hostname: hello
  service:
    name: hello
    port: 8080