
[[constraint]]
  branch = "master"
  name = "github.com/denisenkom/go-mssqldb"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.1"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/vrischmann/envconfig"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
