---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-metrics
  labels:
    app: sample-metrics
    example: monitoring-custom-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-metrics
      example: monitoring-custom-metrics
  template:
    metadata:
      labels:
        app: sample-metrics
        example: monitoring-custom-metrics
    spec:
      containers:
      - name: sample-metrics
        image: europe-docker.pkg.dev/kyma-project/prod/examples/monitoring-custom-metrics:v20230912-0845948c
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 32Mi
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: sample-metrics
  labels:
    app: sample-metrics
    example: monitoring-custom-metrics
spec:
  selector:
    app: sample-metrics
  ports:
  - name: http
    port: 8080
    protocol: TCP
