apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-inlets-token
type: Opaque
data:
  token: {{ .Values.token | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inlets
  labels:
    app: {{ .Release.Name }}-inlets
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}-inlets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-inlets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-inlets
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-inlets
    spec:
      containers:
      - name: inlets
        image: inlets/inlets:2.6.3
        imagePullPolicy: Always
        command: ["inlets"]
        args:
        - "server"
        - "--token-from=/var/inlets/token"
        volumeMounts:
          - name: inlets-token-volume
            mountPath: /var/inlets/
      volumes:
        - name: inlets-token-volume
          secret:
            secretName: {{ .Release.Name }}-inlets-token
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ .Release.Name }}-inlets
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: allow
    methods: ["*"]
    path: .*
  service:
    host: {{ .Release.Name }}-inlets
    name: {{ .Release.Name }}-inlets
    port: 8000
