apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: example-subscription
  labels:
    example: event-subscription-service
spec:
  endpoint: http://event-email-service.<namespace>:3000/v1/events/register
  include_subscription_name_header: true
  event_type: test-event-bus
  event_type_version: v1
  source_id: external-application
