apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-publisher
  labels:
    app: example-publisher
    example: event-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-publisher
  template:
    metadata:
      name: example-publisher
      labels:
        app: example-publisher
        example: event-bus
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: example-publisher
        image: alpine
        imagePullPolicy: IfNotPresent
        args: ['sh', '-c', 'apk add --update curl && while sleep 3600; do :; done']
