config:
  exporters:
    # Reconfigure the OTLP exporter with settings taken from the injected envs
    otlp:
      endpoint: ${OTLP_ENDPOINT}
      headers:
        Authorization: ${AUTH_HEADER}

# Load envs with values from the secret
extraEnvs:
- name: OTLP_ENDPOINT
  valueFrom:
    secretKeyRef:
      name: mySecret
      key: endpoint
- name: AUTH_HEADER
  valueFrom:
    secretKeyRef:
      name: mySecret
      key: authHeaderValue
