global:
  gateway: kyma-gateway
hydraServer:
  serviceName: ory-hydra-oauth2
  namespace: kyma-system
  adminPort: 4445
loginConsent:
  name: oauth2-login-consent
  domainName: kymaIngressDomain
  port: 3000
  image:
    repository: tsmsap/hydra-dex
    tag: test3_1
  dexJwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys
