alertmanager:
  config:
   global:
     resolve_timeout: 5m
   inhibit_rules:
     - source_matchers:
         - 'severity = critical'
       target_matchers:
         - 'severity =~ warning|info'
       equal:
         - 'namespace'
         - 'alertname'
     - source_matchers:
         - 'severity = warning'
       target_matchers:
         - 'severity = info'
       equal:
         - 'namespace'
         - 'alertname'
     - source_matchers:
         - 'alertname = InfoInhibitor'
       target_matchers:
         - 'severity = info'
       equal:
         - 'namespace'
   route:
     group_by: ['namespace']
     group_wait: 30s
     group_interval: 5m
     repeat_interval: 12h
     receiver: 'null'
     routes:
     - receiver: 'null'
       matchers:
         - alertname =~ "InfoInhibitor|Watchdog"
     - continue: true
       match_re:
         severity: critical
       receiver: "slack"
   receivers:
   - name: 'null'
   - name: "slack"
     slack_configs:
     - channel: "<channel-name>"
       send_resolved: true
       api_url: "<api-url>"
       icon_emoji: ":ghost:"
       title: '{{ template "__subject" . }}'
       title_link: 'https://grafana.<cluster-domain>'
       text: '{{ range .Alerts }}`}}<!channel>{{`{{- "\n" -}}`}}{{`{{ .Annotations.description }}`}}{{`{{- "\n" -}}`}}{{`{{ end }}'
   templates:
   - '/etc/alertmanager/config/*.tmpl'
