apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: kiali
spec:
  host: kiali-server
  service:
    name: kiali-server
    port: 20001
  gateway: kyma-system/kyma-gateway
  rules:
    - path: /.*
      methods: ["GET", "POST"]
      accessStrategies:
        - handler: noop
      mutators:
        - handler: noop
