################################################################################
## Turn Off mTLS for hydra server, because Istio Pilot can't fetch
## jwks keys from Hydra Server if mTLS is active.
#################################################################################
kind: Policy
apiVersion: authentication.istio.io/v1alpha1
metadata:
  labels:
  name: {{ .Release.Name }}-policy
  namespace: {{ .Release.Namespace }}
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
  targets:
  - name: {{ .Values.hydraServer.serviceName }}
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Release.Name }}-destinationrule
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.hydraServer.serviceName }}.{{ .Values.hydraServer.namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

