apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.loginConsent.name }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-{{ .Values.loginConsent.name }}
        app: {{ .Release.Name }}-{{ .Values.loginConsent.name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.loginConsent.name }}
          image: {{ .Values.loginConsent.image.repository }}:{{ .Values.loginConsent.image.tag }}
          env:
            - name: HYDRA_ADMIN_URL
              value: http://{{ .Values.hydraServer.serviceName }}.{{ .Values.hydraServer.namespace }}.svc.cluster.local:{{ .Values.hydraServer.adminPort }}
              #The public domain name of the running application in Kyma cluster (used in user-agent redirects)
            - name: DOMAIN
              value: {{ .Values.loginConsent.name }}.{{ .Values.loginConsent.domainName }}
              #The public domain name of the dex in Kyma cluster (used in user-agent redirects)
            - name: DEX_DOMAIN
              value: dex.{{ .Values.loginConsent.domainName }}
            - name: DEX_JWKS_URI
              value: {{ .Values.loginConsent.dexJwksUri }}
            - name: DEX_RESPONSE_TYPE
              value: id_token%20token
            - name: DEX_CLIENT_ID
              value: hydra-integration
            - name: DEX_SCOPE
              value: openid%20profile%20email%20groups
          ports:
          - containerPort: {{ .Values.loginConsent.port }}
