---
kind: Service
apiVersion: v1
metadata:
  name: sample-metrics-8080
  namespace: default
  labels:
    example: monitoring-custom-metrics
spec:
  selector:
    app: sample-metrics
  ports:
  - name: web
    port: 8080
    protocol: TCP