{{ if .Values.examples.serviceBinding.lambda.deploy }}
---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-service-binding-lambda-deploy-{{ randAlphaNum 5 | lower }}"
  labels:
    example: service-binding-lambda
    app: service-binding-lambda-test
    chart: examples
spec:
  serviceAccountName: {{ .Release.Name }}-examples-service-account
  containers:
    - name: service-binding-lambda-deploy
      image: {{ .Values.examples.image }}
      command: ['sh', '-c']
      args:
        - export KYMA_EXAMPLE_ENV="{{ .Release.Namespace }}" || (touch /tmp/healthy && sleep 600) && 
          cd service-binding/lambda || (touch /tmp/healthy && sleep 600) && 
          kubectl apply -f deployment/redis-instance.yaml,deployment/redis-instance-binding.yaml -n $KYMA_EXAMPLE_ENV || (touch /tmp/healthy && sleep 600) && 
          kubectl apply -f deployment/lambda-function.yaml -n $KYMA_EXAMPLE_ENV || (touch /tmp/healthy && sleep 600) &&
          kubectl apply -f deployment/service-binding-usage.yaml -n $KYMA_EXAMPLE_ENV || (touch /tmp/healthy && sleep 600) &&
          touch /tmp/healthy && sleep 600
      readinessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        limits:
          memory: 100Mi
        requests:
          memory: 32Mi
  restartPolicy: Never
---
{{ end }}