apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: orders-service
  labels:
    app: orders-service
    release: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
      release: orders-service
  template:
    metadata:
      labels:
        app: orders-service
        release: orders-service
    spec:
      containers:
        - name: orders-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 10m
              memory: 16Mi
            requests:
              cpu: 16m
              memory: 32Mi
          env:
            - name: APP_PORT
              value: "8080"
            - name: APP_REDIS_PREFIX
              value: "REDIS_"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: orders-service
  labels:
    app: orders-service
    release: orders-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: orders-service
    release: orders-service
