name: event-emitter
namespace: default
runtime: nodejs14
source:
    sourceType: inline
apiRules:
    - name: incomming-http-trigger
      service:
        host: incomming.inclusterevent.wookiee.shoot.canary.k8s-hana.ondemand.com
      rules:
        - methods:
            - GET
          accessStrategies:
            - handler: allow