name: event-emitter
namespace: default
runtime: nodejs14
source:
    sourceType: inline
apiRules:
    - name: incomming-http-trigger
      service:
        host: incomming
      rules:
        - methods:
            - GET
          accessStrategies:
            - handler: allow