apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: redis-client
  labels:
    example: service-binding
spec:
  handler: handler.main
  runtime: nodejs8
  type: HTTP
  deployment:
    spec:
      template:
        spec:
          containers:
          - name: redis-client
  deps: |
    {
      "name": "app",
      "version": "0.0.1",
      "dependencies": {
        "redis":  "2.8.0",
        "double-ended-queue": "2.1.0-0",
        "redis-commands": "1.3.1",
        "redis-parser": "2.6.0"
      }
    }
  function: |
      const redis = require('redis');
      module.exports = {
          main: (event, context) => {
              const client = redis.createClient({host: process.env.HOST, port: process.env.PORT, password: process.env.REDIS_PASSWORD});
              client.info(function (err, reply) {
                  if (err) {
                      return `Error occurred while connecting to redis: ${err} \n`;
                  }
                  console.log(`This page was generated after talking to redis.\n\n` +
                      `Redis info:\n  ${reply}\n`);
              });
          },
      };

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: redis-instance-binding
  labels: 
    example: service-binding   
spec:
  instanceRef:
    name: redis-instance
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: fn-redis-client
  labels:
    example: service-binding
spec:
 serviceBindingRef:
   name: redis-instance-binding
 usedBy:
   kind: function
   name: redis-client
