apiVersion: v1
kind: Service
metadata:
  name: http-db-service
  labels:
    example: service-binding
spec:
  ports:
  - name: http
    port: 8017
  selector:
    example: service-binding
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-db-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        example: service-binding
    spec:
      containers:
      # replace the repository URL with your own repository (e.g. {DockerID}/http-db-service:0.0.x for Docker Hub).
      - image: eu.gcr.io/kyma-project/example/http-db-service:0.0.6
        imagePullPolicy: IfNotPresent
        name: http-db-service
        ports:
        - name: http
          containerPort: 8017
        env:
        - name: dbtype
          # available dbtypes are: [memory, mssql]
          value: "mssql"

---
apiVersion: servicecatalog.kyma.cx/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: mssql-instance-binding-usage
  labels:
    example: service-binding
spec:
 serviceBindingRef:
   name: mssql-instance-binding
 usedBy:
   kind: deployment
   name: http-db-service