{{ if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-examples-service-account
  namespace:  {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-examples-role
  namespace:  {{ .Release.Namespace }}
rules:  
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "pods/exec", "pods/log"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services/proxy"]
    verbs: ["get", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["kubeless.io"]
    resources: ["functions"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["applicationconnector.kyma-project.io"]
    resources: ["eventactivations"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["eventing.kyma-project.io"]
    resources: ["subscriptions"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]    
  - apiGroups: ["config.istio.io"]
    resources: ["rules", "deniers", "checknothings", "egressrules"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"] 
  - apiGroups: ["kubeless.io"]
    resources: ["functions"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: ["servicecatalog.k8s.io"]
    resources: ["serviceinstances", "servicebindings"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: ["servicecatalog.kyma-project.io"]
    resources: ["servicebindingusages"]
    verbs: ["create", "delete", "get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-examples-role-binding
  namespace:  {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-examples-service-account 
    namespace:  {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-examples-role
---
{{ end }}
